<a href="https://colab.research.google.com/github/yuiijie/assignment6.1/blob/main/9_1_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 9.1

> Replace all TODOs with your code. Do not change any other code.

In [2]:
# Do not edit this cell

import numpy as np
import pandas as pd

## Numpy

### Task 1

Create a 1D numpy array with elements [1, 2, 3, 4, 5]. Do it in two different ways.


In [3]:
res = np.array([1, 2, 3, 4, 5])

print(res)

[1 2 3 4 5]


In [4]:
res2 = np.arange(1, 6)

print(res2)

[1 2 3 4 5]


### Task 2

Create a 2D numpy array with shape (3, 5) filled with random integers between 1 and 100.

In [5]:
res3 = np.random.randint(1, 100, size=(3, 5))

print(res3)

[[56 63  6 47 88]
 [12 33 98 86 90]
 [61 43 89 97 97]]


### Task 3

Print the first row of array `res3`.

In [6]:
print(res3[:1])

[[56 63  6 47 88]]


### Task 4

Access the last column of array `res3`. Assume that the array may be of any 2D shape.

In [7]:
print(res3[:, -1])

[88 90 97]


### Task 5

Find the min, max, and sum of elements of the second column of array `res3`.

In [8]:
# Min
res_min = np.min(res3[:, 1], axis=0)

print('min =', res_min)

min = 33


In [9]:
# Max
res_max = np.max(res3[:, 1], axis=0)

print('max =', res_max)

max = 63


In [10]:
# Sum
res_sum = np.sum(res3[:, 1], axis=0)

print('sum =', res_sum)

sum = 139


### Task 6

Tabulate the function

$$f(x) = e^{2x}$$

on interval `[0, 1]` with step 0.1.

By "tabulate" we mean that we want to have a table (1D array), where on the first position we will have the function value for 0, on the second position 0.1, and so on.

In [14]:
x = np.arange(0, 1.01, 0.1)
f_x = np.exp(2 * x)

print(f_x)

[1.         1.22140276 1.4918247  1.8221188  2.22554093 2.71828183
 3.32011692 4.05519997 4.95303242 6.04964746 7.3890561 ]


## Pandas

We will be working on the classic dataset for beginner data scientists: Titanic passengers.

### Task 7

Load the dataset from the following URL: https://web.stanford.edu/class/cs102/datasets/Titanic.csv

In [52]:
df = pd.read_csv('https://web.stanford.edu/class/cs102/datasets/Titanic.csv')



### Task 8

Let's see the series/columns present in the data frame.

Also, let's inspect the first ten rows of data.

In [53]:
print(list(df.columns.values))

['last', 'first', 'gender', 'age', 'class', 'fare', 'embarked', 'survived']


In [54]:
print(df.head(10))

        last                                       first gender   age  class  \
0     Braund                             Mr. Owen Harris      M  22.0      3   
1    Cumings  Mrs. John Bradley (Florence Briggs Thayer)      F  38.0      1   
2  Heikkinen                                  Miss Laina      F  26.0      3   
3   Futrelle          Mrs. Jacques Heath (Lily May Peel)      F  35.0      1   
4      Allen                           Mr. William Henry      M  35.0      3   
5      Moran                                   Mr. James      M   NaN      3   
6   McCarthy                               Mr. Timothy J      M  54.0      1   
7    Palsson                        Master Gosta Leonard      M   2.0      3   
8    Johnson    Mrs. Oscar W (Elisabeth Vilhelmina Berg)      F  27.0      3   
9     Nasser                 Mrs. Nicholas (Adele Achem)      F  14.0      2   

      fare     embarked survived  
0   7.2500  Southampton       no  
1  71.2833    Cherbourg      yes  
2   7.9250  So

### Task 9

Add a new column - full name - it should be a concat of the first and last name.

In [55]:
df["full name"] =  df["first"] + ' ' + df["last"]
print(df.head(3))

        last                                       first gender   age  class  \
0     Braund                             Mr. Owen Harris      M  22.0      3   
1    Cumings  Mrs. John Bradley (Florence Briggs Thayer)      F  38.0      1   
2  Heikkinen                                  Miss Laina      F  26.0      3   

      fare     embarked survived  \
0   7.2500  Southampton       no   
1  71.2833    Cherbourg      yes   
2   7.9250  Southampton      yes   

                                           full name  
0                             Mr. Owen Harris Braund  
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  
2                               Miss Laina Heikkinen  


### Task 10

Remove the two original columns - last, first.

In [56]:
df = df.drop(columns=['last', 'first'])
df = df[['full name', 'gender', 'age', 'class', 'fare', 'embarked', 'survived']]
print(df.head(3))

                                           full name gender   age  class  \
0                             Mr. Owen Harris Braund      M  22.0      3   
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...      F  38.0      1   
2                               Miss Laina Heikkinen      F  26.0      3   

      fare     embarked survived  
0   7.2500  Southampton       no  
1  71.2833    Cherbourg      yes  
2   7.9250  Southampton      yes  


### Task 11

Calculate the total number of survivors in the dataset.

In [72]:
total_survivors = df['survived'].value_counts()
print(total_survivors)

survived
no     549
yes    342
Name: count, dtype: int64
